homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://192.168.1.53:1883'
serial:
  port: /dev/ttyACM0
devices:
  '0x00158d0002c63968':
    friendly_name: doorSensorXiaomi_x1
    retain: false
  '0x00158d0002d7740f':
    friendly_name: '0x00158d0002d7740f'
    retain: false
